
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Feb 19 2025 16:31:53 IST (Feb 19 2025 11:01:53 UTC)

// Verification Directory fv/PWM 

module PWM(clkin_pad, reset_pad, duty_cycle_pad, out_pad);
  input clkin_pad, reset_pad;
  input [7:0] duty_cycle_pad;
  output out_pad;
  wire clkin_pad, reset_pad;
  wire [7:0] duty_cycle_pad;
  wire out_pad;
  wire [7:0] duty_cycle;
  wire [7:0] counter;
  wire clkin, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, out, read_clk, reset;
  pc3c01 pc3c01_1(.CCLK (read_clk), .CP (clkin));
  pc3d01 pc3d01_1(.PAD (clkin_pad), .CIN (read_clk));
  pc3d01 pc3d01_2(.PAD (reset_pad), .CIN (reset));
  pc3d01 pc3d01_3(.PAD (duty_cycle_pad[7]), .CIN (duty_cycle[7]));
  pc3d01 pc3d01_4(.PAD (duty_cycle_pad[6]), .CIN (duty_cycle[6]));
  pc3d01 pc3d01_5(.PAD (duty_cycle_pad[5]), .CIN (duty_cycle[5]));
  pc3d01 pc3d01_6(.PAD (duty_cycle_pad[4]), .CIN (duty_cycle[4]));
  pc3d01 pc3d01_7(.PAD (duty_cycle_pad[3]), .CIN (duty_cycle[3]));
  pc3d01 pc3d01_8(.PAD (duty_cycle_pad[2]), .CIN (duty_cycle[2]));
  pc3d01 pc3d01_9(.PAD (duty_cycle_pad[1]), .CIN (duty_cycle[1]));
  pc3d01 pc3d01_10(.PAD (duty_cycle_pad[0]), .CIN (duty_cycle[0]));
  pc3o05 pc3o05_1(.I (out), .PAD (out_pad));
  
  //FLOORPLANNING Power Pads 
  pvdi pvdi_VDD_CORE_1 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE)); 
  pv0i pv0i_VSS_CORE_1 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda pvda_VDDO_CORE_1 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a pv0a_VSSO_CORE_1 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  
  
  pvdi pvdi_VDD_CORE_2 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE)); 
  pv0i pv0i_VSS_CORE_2 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda pvda_VDDO_CORE_2 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a pv0a_VSSO_CORE_2 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  
  pvdi pvdi_VDD_CORE_3 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE)); 
  pv0i pv0i_VSS_CORE_3 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda pvda_VDDO_CORE_3 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a pv0a_VSSO_CORE_3 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  
  pvdi pvdi_VDD_CORE_4 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE)); 
  pv0i pv0i_VSS_CORE_4 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda pvda_VDDO_CORE_4 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a pv0a_VSSO_CORE_4 (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  


  oaim22d1 g706__2398(.A1 (n_32), .A2 (counter[7]), .B1 (n_32), .B2
       (counter[7]), .ZN (n_33));
  dfcrq1 \counter_reg[6] (.CDN (n_4), .CP (clkin), .D (n_1), .Q
       (counter[6]));
  nd02d0 g711__5107(.A1 (n_31), .A2 (counter[6]), .ZN (n_32));
  ah01d1 g712__6260(.A (n_26), .B (counter[5]), .CO (n_31), .S (n_30));
  dfcrq1 out_reg(.CDN (n_4), .CP (clkin), .D (n_29), .Q (out));
  ora311d1 g714__4319(.A (n_28), .B (n_19), .C1 (n_13), .C2
       (duty_cycle[5]), .C3 (n_8), .Z (n_29));
  aoi22d1 g716__8428(.A1 (n_25), .A2 (n_14), .B1 (n_12), .B2 (n_11),
       .ZN (n_28));
  ah01d1 g717__5526(.A (n_22), .B (counter[4]), .CO (n_26), .S (n_27));
  aoi21d1 g718__6783(.A (n_24), .B1 (duty_cycle[4]), .B2 (n_3), .ZN
       (n_25));
  cg01d1 g720__3680(.A (duty_cycle[3]), .B (n_2), .CI (n_21), .CO
       (n_24));
  aoi21d1 g721__1617(.A (n_22), .B1 (n_18), .B2 (n_2), .ZN (n_23));
  cg01d1 g723__2802(.A (duty_cycle[2]), .B (n_6), .CI (n_20), .CO
       (n_21));
  nr02d0 g724__1705(.A1 (n_18), .A2 (n_2), .ZN (n_22));
  aoi211d1 g725__5122(.A (n_15), .B (n_17), .C1 (n_10), .C2
       (counter[1]), .ZN (n_20));
  nd13d1 g726__8246(.A1 (duty_cycle[4]), .A2 (n_14), .A3 (counter[4]),
       .ZN (n_19));
  dfcrq1 \counter_reg[1] (.CDN (n_4), .CP (clkin), .D (n_16), .Q
       (counter[1]));
  nd02d0 g730__7098(.A1 (n_17), .A2 (counter[2]), .ZN (n_18));
  ah01d1 g731__6131(.A (counter[1]), .B (counter[0]), .CO (n_17), .S
       (n_16));
  aoim31d1 g732__1881(.A (duty_cycle[1]), .B1 (n_10), .B2 (counter[1]),
       .B3 (counter[0]), .ZN (n_15));
  aoi21d1 g733__5115(.A (n_13), .B1 (duty_cycle[5]), .B2 (n_8), .ZN
       (n_14));
  oai21d1 g734__7482(.A (n_11), .B1 (n_9), .B2 (counter[6]), .ZN
       (n_13));
  oaim22d1 g735__4733(.A1 (duty_cycle[7]), .A2 (n_5), .B1 (n_9), .B2
       (counter[6]), .ZN (n_12));
  nd02d0 g737__6161(.A1 (duty_cycle[7]), .A2 (n_5), .ZN (n_11));
  inv0d0 g738(.I (duty_cycle[0]), .ZN (n_10));
  inv0d0 g739(.I (duty_cycle[6]), .ZN (n_9));
  inv0d0 g744(.I (reset), .ZN (n_4));
  ora21d1 g2__9315(.A (n_32), .B1 (n_31), .B2 (counter[6]), .Z (n_1));
  ora21d1 g747__9945(.A (n_18), .B1 (n_17), .B2 (counter[2]), .Z (n_0));
  dfcrb1 \counter_reg[5] (.CDN (n_4), .CP (clkin), .D (n_30), .Q
       (counter[5]), .QN (n_8));
  dfcrb1 \counter_reg[0] (.CDN (n_4), .CP (clkin), .D (n_7), .Q
       (counter[0]), .QN (n_7));
  dfcrb1 \counter_reg[2] (.CDN (n_4), .CP (clkin), .D (n_0), .Q
       (counter[2]), .QN (n_6));
  dfcrb1 \counter_reg[7] (.CDN (n_4), .CP (clkin), .D (n_33), .Q
       (counter[7]), .QN (n_5));
  dfcrb1 \counter_reg[4] (.CDN (n_4), .CP (clkin), .D (n_27), .Q
       (counter[4]), .QN (n_3));
  dfcrn1 \counter_reg[3] (.CDN (n_4), .CP (clkin), .D (n_23), .QN
       (n_2));
endmodule
